env:
 - MARATHONVERSION: 1.3.0
 - MARATHONVERSION: 1.1.2
 - MARATHONVERSION: 0.15.3
 - MARATHONVERSION: 0.14.1
 - MARATHONVERSION: 0.13.1
 - MARATHONVERSION: 0.11.1
 - MARATHONVERSION: 0.10.1

language: python
python:
  - 2.7
install:
  - pip install tox
script:
  - make test
  - ./itests/install-marathon.sh
  - /etc/init.d/zookeeper start
  - ./itests/start-marathon.sh &
  - make itests

# Work around travis-ci/travis-ci#5227
addons:
  hostname: localhost
